DX-914: which java
Why is Java suddenly available?

diff --git a/.github/workflows/no-java.yml b/.github/workflows/no-java.yml
--- a/.github/workflows/no-java.yml
+++ b/.github/workflows/no-java.yml
@@ -18,5 +18,7 @@ jobs:
     - name: Bundle install
       run: bundle install --jobs 4 --retry 3
 
+    - run: which java || echo "Java not found"
+
     - name: RSpec
       run: bundle exec rspec --tag no_java
