Install PlantUML with Maven
Rework some code and the workflow to have plantuml*.jar installed by Maven at build time instead of having it reside in the repository.

diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -9,21 +9,18 @@ on:
   pull_request:
 
 jobs:
-  build:
-    name: Build, Test and Publish Ruby Gem
+  version:
     runs-on: ubuntu-latest
+
+    outputs:
+      version: ${{ steps.gemversion.outputs.version }}
 
     steps:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
 
-    - name: Fetch all history for all tags and branches
-      run: |
-        git fetch --prune --tags
-        echo "REF: ${{ github.ref }}"
-
-    - name: Install GitVersion
+    - name: Setup GitVersion
       uses: gittools/actions/gitversion/setup@v0.9.2
       if: startsWith(github.ref, 'refs/tags/') != true # Only use GitVersion for unstable builds
       with:
@@ -54,15 +51,62 @@ jobs:
 
           core.setOutput('version', gemVersion);
 
-    - name: Set up Ruby 2.6
+  plantuml:
+    needs: version
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Setup Java
+      uses: actions/setup-java@v1
+      with:
+        java-version: 14
+
+    - name: Cache Maven dependencies
+      uses: actions/cache@v2
+      with:
+        path: ~/.m2/repository
+        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+        restore-keys: ${{ runner.os }}-maven-
+
+    - name: Version stamp
+      run: mvn versions:set -DnewVersion=${{ needs.version.outputs.version }}
+
+    - name: Maven install
+      run: mvn install
+
+    - name: Upload plantuml.jar artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: plantuml.jar
+        path: ~/.m2/repository/**/plantuml*.jar
+
+  gem:
+    needs: [version, plantuml]
+    runs-on: ubuntu-latest
+
+    outputs:
+      name: ${{ steps.gem.outputs.name }}
+
+    steps:
+    - uses: actions/download-artifact@v2
+      with:
+        name: plantuml.jar
+        path: bin/
+
+    - name: Version stamp
+      run: sed -i -e 's/0.0.1.dev/${{ needs.version.outputs.version }}/g' ./lib/kramdown-plantuml/version.rb
+
+    - name: Set up Ruby 2.7
       uses: actions/setup-ruby@v1
       with:
-        ruby-version: 2.6.x
+        ruby-version: 2.7.x
 
     - name: Setup Graphviz
       uses: kamiazya/setup-graphviz@v1
 
-    - name: Cache dependencies
+    - name: Cache Ruby gems
       uses: actions/cache@v1
       with:
         path: vendor/bundle
@@ -79,14 +123,10 @@ jobs:
       run: bundle exec rubocop --fail-level warning --display-only-fail-level-offenses
 
     - name: Test with Rake
-      env:
-        GEM_VERSION: ${{ steps.gemversion.outputs.version }}
       run: bundle exec rake
 
     - name: Build gem
       id: gem
-      env:
-        GEM_VERSION: ${{ steps.gemversion.outputs.version }}
       run: |
         GEM_BUILD_NAME=$(gem build kramdown-plantuml.gemspec | awk '/File/ {print $2}')
         echo "Gem filename: '${GEM_BUILD_NAME}'"
@@ -97,6 +137,15 @@ jobs:
       with:
         name: ${{ steps.gem.outputs.name }}
         path: ${{ steps.gem.outputs.name }}
+
+  publish:
+    needs: [version, gem]
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/download-artifact@v2
+      with:
+        name: ${{ needs.gem.outputs.name }}
 
     - name: Publish to GPR
       env:
@@ -110,8 +159,8 @@ jobs:
         set -e
         gem push --KEY github \
                  --host https://rubygems.pkg.github.com/${OWNER} \
-                 ${{ steps.gem.outputs.name }} \
-          || echo "push failed ($?) probably due to version '${{ steps.gemversion.outputs.version }}' already existing in GPR."
+                 ${{ needs.gem.outputs.name }} \
+          || echo "push failed ($?) probably due to version '${{ needs.version.outputs.version }}' already existing in GPR."
 
     - name: Publish to RubyGems
       if: startsWith(github.ref, 'refs/tags/') # Only publish tagged commits
@@ -122,4 +171,4 @@ jobs:
         touch $HOME/.gem/credentials
         chmod 0600 $HOME/.gem/credentials
         printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
-        gem push ${{ steps.gem.outputs.name }}
+        gem push ${{ needs.gem.outputs.name }}
